WebUI/Controllers/AdminController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IPhoneRepository repository;

        public AdminController(IPhoneRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Phones);
        }

        public ViewResult Edit(int phoneId)
        {
            Phone phone = repository.Phones.FirstOrDefault(p => p.PhoneId == phoneId);
            return View(phone);
        }

        [HttpPost]
        //public ActionResult Edit(Phone phone, HttpPostedFileBase image = null)
        public ActionResult Edit(Phone phone, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    phone.ImageMimeType = image.ContentType;
                    phone.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(phone.ImageData, 0, image.ContentLength);
                }
                repository.SavePhone(phone);
                TempData["message"] = string.Format("Изменение информации о товаре \"{0} {1}\" сохранены", phone.Mark, phone.Model);
                return RedirectToAction("Index");
            }
            else
            {
                // Что-то не так со значениями данных
                return View(phone);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Phone());
        }

        [HttpPost]
        public ActionResult Delete(int phoneId)
        {
            Phone deletedPhone = repository.DeletePhone(phoneId);
            if (deletedPhone!=null)
            {
                TempData["message"] = string.Format("Товар \"{0} {1}\" был удален", deletedPhone.Mark, deletedPhone.Model);
            }
            return RedirectToAction("Index");
        }

    }
}

WebUI/Controllers/PhonesController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class PhonesController : Controller
    {
        private IPhoneRepository repository;
        public int pageSize = 4;


        public PhonesController(IPhoneRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            PhonesListViewModel model = new PhonesListViewModel
            {
                Phones = repository.Phones
                .Where(b => category == null || b.Category == category)
                .OrderBy(phone => phone.PhoneId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                        repository.Phones.Count() : 
                        repository.Phones.Where(phone => phone.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public FileContentResult GetImage(int phoneId)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(p => p.PhoneId == phoneId);

            if (phone != null)
            {
                return File(phone.ImageData, phone.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult Info(int Id, string returnUrl)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(p => p.PhoneId == Id);
            
            return View(phone);
        }
    }
}

WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Phone

@{
    ViewBag.Title = "Админ панель: редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    //HtmlHelper.ClientValidationEnabled = false;
    //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
}

<div class="panel">
    <div class="panel-heading">
        <h3>Редактирование товара @Model.Mark @Model.Model</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.PhoneId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
                {
                    switch (property.PropertyName)
                    {
                        case "PhoneId":
                        case "ImageData":
                        case "ImageMimeType":
                            //
                            break;
                        default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Картинка</label>
                    <a class='btn' href='javascript:;'>
                        Выберите файл...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">Нет картинки</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Phones", new { Model.PhoneId })" />
                }
            </div>
        </div>

        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Phone>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        Список товаров
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.PhoneId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mark)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Model)
                </th>
                <th class="text-right">
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th class="text-center">
                    Действия
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">
                        @item.PhoneId
                    </td>
                    <td>
                        @Html.ActionLink(item.Mark, "Edit", new { item.PhoneId })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td class="text-right">
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("PhoneId", item.PhoneId)
                            <input type="submit" class="btn btn-default btn-xs" value="Удалить" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>

    <div class="panel-footer">
        @Html.ActionLink("Добавить", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>