WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IPhoneRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController (IPhoneRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index (Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        //public Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}

        public RedirectToRouteResult AddToCart(Cart cart, int phoneId, string returnUrl)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(b => b.PhoneId == phoneId);
            if (phone != null)
            {
                cart.AddItem(phone, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int phoneId, string returnUrl)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(b => b.PhoneId == phoneId);
            if (phone != null)
            {
                cart.RemoveLine(phone);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary (Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }

            else
            {
                return View(new ShippingDetails());
            }
        }

    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IPhoneRepository repository;

        public NavController (IPhoneRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> typeOfPhone = repository.Phones
                .Select(phone => phone.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView("FlexMenu", typeOfPhone);
        }
    }
}

WebUI/Controllers/PhonesController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class PhonesController : Controller
    {
        private IPhoneRepository repository;
        public int pageSize = 4;


        public PhonesController(IPhoneRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            PhonesListViewModel model = new PhonesListViewModel
            {
                Phones = repository.Phones
                .Where(b => category == null || b.Category == category)
                .OrderBy(phone => phone.PhoneId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                        repository.Phones.Count() : 
                        repository.Phones.Where(phone => phone.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public FileContentResult GetImage(int phoneId)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(p => p.PhoneId == phoneId);

            if (phone != null)
            {
                return File(phone.ImageData, phone.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ActionResult Info(int Id, string returnUrl)
        {
            Phone phone = repository.Phones
                .FirstOrDefault(p => p.PhoneId == Id);
            
            return View(phone);
        }
    }
}

WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-3.1.1.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div class="container">
        <div">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
            @RenderBody()
        </div>
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-3.1.1.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("List", "Phones")">Интернет-магазин</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @*<li><a href="#">Личный кабинет</a></li>*@
                    <li>@Html.Action("Summary", "Cart")</li>
                </ul>
            </div>
        </div>
    </div> 
    <div class="container w">
        <div class="row text-center">
            <br /><br />
            <div class="visible-xs">
                @Html.Action("Menu", "Nav", new { horizontalNav = true })
            </div>
            <div id="categories" class="col-xs-3 hidden-xs">
                @Html.Action("Menu", "Nav")
            </div>
            <div class="col-md-8 col-xs-12">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="first-footer">
                    <div class="col-md-4 col-md-offset-1 col-xs-8">
                        <h4>Информация</h4>
                        <ul class="list-unstyled">
                            <li><a href="#"> Гарантия</a></li>
                            <li><a href="#"> Доставка</a></li>
                            <li><a href="#"> Политика</a></li>
                            <li><a href="@Url.Action("AboutUs","Company")">О нас</a></li>
                            <li><a href="@Url.Action("Contacts","Company")"> Контакты</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4 col-xs-8">
                        <h4>Социальные сети</h4>
                        <ul class="list-unstyled">
                            <li>
                                <a href="https://vk.com/" target="_blank"><i class="fa fa-vk" aria-hidden="true"></i></a>
                                <a href="https://www.facebook.com" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="https://twitter.com/" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="https://www.instagram.com/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-xs-8">
                        <h4>Служба поддержки</h4>
                        <ul class="list-unstyled">
                            <li><a href=@Url.Action("FeedBack", "Company")> Связаться с нами</a></li>
                            <li><a href="#"> Возврат товара</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

WebUI/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/scripts/jquery-3.1.1.min.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("List", "Phones")">Интернет-магазин</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @*<li><a href="#">Личный кабинет</a></li>*@
                    <li>@Html.Action("Summary", "Cart")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container w">
        <div class="row text-center">
            <div class="col-md-8 col-md-offset-2 col-xs-12">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="first-footer">
                    <div class="col-md-4 col-md-offset-1 col-xs-8">
                        <h4>Информация</h4>
                        <ul class="list-unstyled">
                            <li><a href="#"> Гарантия</a></li>
                            <li><a href="#"> Доставка</a></li>
                            <li><a href="#"> Политика</a></li>
                            <li><a href="@Url.Action("AboutUs","Company")">О нас</a></li>
                            <li><a href="@Url.Action("Contacts","Company")"> Контакты</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4 col-xs-8">
                        <h4>Социальные сети</h4>
                        <ul class="list-unstyled">
                            <li>
                                <a href="https://vk.com/" target="_blank"><i class="fa fa-vk" aria-hidden="true"></i></a>
                                <a href="https://www.facebook.com" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="https://twitter.com/" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                                <a href="https://www.instagram.com/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-xs-8">
                        <h4>Служба поддержки</h4>
                        <ul class="list-unstyled">
                            <li><a href=@Url.Action("FeedBack", "Company")> Связаться с нами</a></li>
                            <li><a href="#"> Возврат товара</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

WebUI/Views/Shared/_PhoneSummary.cshtml
@model Domain.Entities.Phone

<div class="panel panel-info">
    <div class="panel-body">
        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-left: 10px">
                <img class="img-thumbnail" width="180" height="150"
                     src="@Url.Action("GetImage", "Phones", new { Model.PhoneId })" />
            </div>
        }
        <h3>
            <strong>@Model.Mark @Model.Model</strong>
            <span class="pull-right label label-info">@Model.Price.ToString("# руб")</span>
            @*<br />
            <span class="pull-right label label-primary">Подробнее о товаре</span>*@
        </h3>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.PhoneId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="В корзину" />
            </div>
        }
        <a href= @Url.Action("Info", "Phones", new { Id = Model.PhoneId })>
            Подробнее о товаре
        </a>

        @*<span>@Html.ActionLink("Подробнее о товаре","Info","Phones", new { Model.PhoneId })</span>*@
        @*<span class="lead">@Model.Description</span>*@
    </div>
</div>